theme: jekyll-theme-minimal
title: Trump-Russia Collusion Network (Abramson 2018)
description: Donald Trump, Tevfik Arif, and Felix Sater at 2007 Trump Soho launch party 2007 (Source: Bloomberg).
logo: /trumplaunch.jpeg
